# 분산 훈련을 위한 기본 설정
NUM_GPUS=4  # 사용할 GPU 수
NODE_RANK=0  # 현재 노드의 순위 (멀티 노드 훈련 시 필요)
NUM_NODES=1  # 사용할 노드 수 (멀티 노드 훈련 시 필요)
MASTER_ADDR=localhost  # 마스터 노드의 주소
MASTER_PORT=25680  # 마스터 노드의 포트
CUDA_VISIBLE_DEVICES=2,3,4,5
# NUM_CONCLUSIONS=2 # NUMBER OF CONCLUSIONS GENERATED BY LLM (beam_num_vlm)
# NUM_LLM_PREMISES=5 # NUMBER OF LLM PREMISES
# NUM_OBJECT_PREMISES=5 # NUMBER OF OBJECT PREMISES

for NUM_CONCLUSIONS in $(seq 2 2)
do
    for NUM_PREMISES in $(seq 2 2)
    do
        # if [ $NUM_CONCLUSIONS -eq 2 ] && [ $NUM_PREMISES -eq 5 ]; then
        #     continue
        # fi
        CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES torchrun \
            --nproc_per_node=$NUM_GPUS \
            --nnodes=$NUM_NODES \
            --node_rank=$NODE_RANK \
            --master_addr=$MASTER_ADDR \
            --master_port=$MASTER_PORT \
            trainer/trainer_v7_logic_with_image_premise.py \
            --name="sciqa_test_c2_p2" \
            --data="scienceqa" \
            --data_path="/data5/solomon/ScienceQA/data/scienceqa/pid_splits.json" \
            --beam_num_vlm=2 \
            --num_object_premises=2 \
            --num_llm_premises=2\
     
        # break
    done
    # break
done


            # --name="sciqa_v7_c${NUM_CONCLUSION}_p${SNUM_PREMISES}" \