# 분산 훈련을 위한 기본 설정
NUM_GPUS=2  # 사용할 GPU 수
NODE_RANK=0  # 현재 노드의 순위 (멀티 노드 훈련 시 필요)
NUM_NODES=1  # 사용할 노드 수 (멀티 노드 훈련 시 필요)
MASTER_ADDR=localhost  # 마스터 노드의 주소
MASTER_PORT=25680  # 마스터 노드의 포트
CUDA_VISIBLE_DEVICES=1,2
NUM_CONCLUSIONS=2 # NUMBER OF CONCLUSIONS GENERATED BY LLM (beam_num_vlm)
NUM_LLM_PREMISES=5 # NUMBER OF LLM PREMISES
NUM_OBJECT_PREMISES=5 # NUMBER OF OBJECT PREMISES

# Python 스크립트 실행
# CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES torchrun \
#     --nproc_per_node=$NUM_GPUS \
#     --nnodes=$NUM_NODES \
#     --node_rank=$NODE_RANK \
#     --master_addr=$MASTER_ADDR \
#     --master_port=$MASTER_PORT \
#     trainer/trainer_v7_logic_with_image_premise_gatum.py \
#     --name='model_v7_aokvqa_c2_p5_result'\
#     --data='aokvqa'\
#     --data_path='/data2/KJE/VQA/aokvqa/aokvqa/aokvqa_v1p0_val.json'\
#     --beam_num_vlm=$NUM_CONCLUSION\
#     --num_object_premises=$NUM_OBJECT_PREMISES\
#     --num_llm_premises=$NUM_LLM_PREMISES


for NUM_CONCLUSIONS in $(seq 1 1)
do
    for NUM_PREMISES in $(seq 1 1)
    do
        # if [ $NUM_CONCLUSIONS -eq 2 ] && [ $NUM_PREMISES -eq 5 ]; then
        #     continue
        # fi
        CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES torchrun \
            --nproc_per_node=$NUM_GPUS \
            --nnodes=$NUM_NODES \
            --node_rank=$NODE_RANK \
            --master_addr=$MASTER_ADDR \
            --master_port=$MASTER_PORT \
            trainer/trainer_v7_logic_with_image_premise_gatum_clip.py \
            --name="model_v7_aokvqa_c${NUM_CONCLUSIONS}_p${NUM_PREMISES}_result" \
            --data="aokvqa" \
            --data_path="/data2/KJE/VQA/aokvqa/aokvqa/aokvqa_v1p0_val.json" \
            --beam_num_vlm=${NUM_CONCLUSIONS} \
            --num_object_premises=${NUM_PREMISES} \
            --num_llm_premises=${NUM_PREMISES}
        # break
    done
    # break
done